#!/usr/bin/env bash
# Passing domain and subdomain parameters, display information for the specified subdomain

RECORD_TYPE=
DESTINATION=

info_dns() {
		SUBDM="."
		SUBDM="$1""$SUBDM""$2"
		INFO="$(dig "$SUBDM" | grep -A1 "ANSWER SECTION" | tail -1)"
		RECORD_TYPE="$(echo "$INFO" | awk '{print $4}')"
		DESTINATION="$(echo "$INFO" | awk '{print $5}')"
		echo "The subdomain ""$1"" is a ""$RECORD_TYPE"" record and points to ""$DESTINATION"
}

if [ "$2" ];
then
		info_dns "$2" "$1"
else
		info_dns "www" "$1"
		info_dns "lb-01" "$1"
		info_dns "web-01" "$1"
		info_dns "web-02" "$1"
fi
