#!/usr/bin/env bash
# Script that Transfers a file from the actual clietn to a server
if [ "$#" -ne 4 ]; then
	 echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi

scp -i "$4" -o "StrictHostKeyChecking no" "$1" "$3"@"$2":~/"$1"
