#!/usr/bin/env bash
# Install and configure and nginx web server
apt-get update -y
apt-get install nginx -y
ufw allow 'Nginx HTTP'
ufw allow 'OpenSSH'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
systemctl start nginx