#!/usr/bin/env bash
# Creates a nginx server and configures redirection
apt-get update -y
apt-get install nginx -y
ufw allow 'Nginx HTTP'
ufw allow 'OpenSSH'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx start

redir="server_name _;\nrewrite ^\/redirect_me\$ https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;\n"
sed -i "s/server_name _;/$redir/g" /etc/nginx/sites-available/default
service nginx restart
